title = "sis input"

[Job]
type = "MD"

[Files]
      [Files.In]
      ff = "./para.ff"
      fasta = "T2S2HP.fasta"
      pdb_ini = "T2S2HP_random.pdb"
      bpl = "T2S2HP.bpl"

      [Files.Out]
      types = ["bp", "bpe", "bpall"]
      prefix = "./test_T2S2HP_bpl"

[Condition]
      tempK = 348.15
      rng_seed = 123

[MD]
integrator = "GJF-2GJ"
dt = 0.05
nstep = 50000
#nstep = 1000000000
nstep_save = 10000
neighbor_list_margin = 10.0
viscosity_Pas = 0.00001

#[Electrostatic]
ionic_strength = 0.15
cutoff_type = 2
cutoff = 10.0
no_charge = [1, 27]
length_per_charge = 4.38178046

[Basepair]
model = 5
min_loop = 3
nstep_MC = 0

[Progress]
step = 1000
