title = "T2S2 HP, DCD mode, temperature independent"

[job]
type = "DCD"

[files]
      [files.in]
      ff = "./sis_dih_ReB_NN.ff"
      fasta = "T2S2HP.fasta"
      dcd = "./test_T2S2HP.dcd"

      [files.out]
      types = []
      prefix = "./test_T2S2HP_temp_independent"

[condition]
      #tempK = 348.15
      tempK = 300.00
      rng_seed = 123
      temp_independent = 1
      tempK_ref = 310.00

[Electrostatic]
ionic_strength = 0.15
cutoff_type = 2
cutoff = 10.0
#no_charge = [1, 27]
length_per_charge = 4.38178046

[Basepair]
model = 5
min_loop = 3
max_bp_per_nt = 1

[Progress]
step = 1000
