title = "sis input"

[job]
type = "MD"

[files]
      [files.in]
      ff = "./rna_cg1_para3.ff"
      fasta = "T2S2HP.fasta"
      pdb_ini = "T2S2HP_random.pdb"

      [files.out]
      types = ["bp", "bpe", "bpall"]
      prefix = "./test_T2S2HP"

[condition]
      tempK = 348.15
      rng_seed = 123

[MD]
integrator = "GJF-2GJ"
dt = 0.05
nstep = 500000
nstep_save = 10000
neighbor_list_margin = 10.0
viscosity_Pas = 0.00001

[Progress]
step = 1000
