title = "sis input"

[Job]
type = "MD"
#type = "CHECK_FORCE"

[Files]
      [Files.In]
      ff = "./sis_dih_ReB_NN.ff"
      fasta = "T2S2HP.fasta"
      xyz_ini = "T2S2HP_random.xyz"

      [Files.Out]
      types = ["bpcoef", "bp", "bpe", "bpall"]
      prefix = "./test_T2S2HP"

[Condition]
      #tempK = 348.15
      tempK = 300.00
      rng_seed = 123

[MD]
integrator = "GJF-2GJ"
dt = 0.05
nstep = 50000
#nstep = 1000000000
nstep_save = 100
neighbor_list_margin = 10.0
viscosity_Pas = 0.00001

[Electrostatic]
ionic_strength = 0.15
cutoff_type = 2
cutoff = 10.0
#no_charge = [1, 27]
length_per_charge = 4.38178046

[Basepair]
model = 5
min_loop = 3
max_bp_per_nt = 1

[Progress]
step = 1000
