title = "sis input"

[job]
type = "MD"

[files]
    [files.in]
    ff = "../rna_cg1.ff"
    pdb_ini = "./cag47_4.pdb"

    [files.out]
    types = ["bp",]
    prefix = "./test_md"

[repeat]
n_repeat = 47
n_chain = 4

[condition]
tempK = 310.15

[PBC_box]
x = 809.972
y = 809.972
z = 809.972

[MD]
integrator = "GJF-2GJ"
viscosity_Pas = 0.00001
dt = 0.5
nstep = 100
nstep_save = 10
