title = "sis input"

[job]
type = "MD"
   # Aveilable options:
   #    "MD"
   #    "DCD"
   #    "CHECK_FORCE"

[files]
      [files.in]
      ff = "./rna_cg1_para2.ff"
         # Force-field file. Required.

      fasta = "./beta-globin.fasta"
         # FASTA sequence file. Required unless [repeat] section is specified.

      pdb_ini = "initial.pdb"
      xyz_ini = "initial.xyz"
         # File for initial structure. Only one of them is required.
         # Only coordinates will be read, and any sequence information written in these files will be ignored.

      dcd = "./trajectory.dcd"
         # DCD file to read. Required if type = "DCD" in [job].

      anneal = "./annealing_schedule.txt"
         # Annealing-schedule file.
         # Required only when opt_anneal > 1 in [condition].

      [files.out]
      types = ["bp", "bpe", "bpall"]
      prefix = "./test"

[condition]
tempK = 310.15
rng_seed = 123

opt_anneal = 1
   # (optional) flag for simulated annealing.
   # 0: No annealing (default)
   # 1: Annealing (anneal is required in [files.in])

[repeat]
n_repeat = 47
n_chain = 64

[PBC_box]
x = 809.972
y = 809.972
z = 809.972

[MD]
integrator = "GJF-2GJ"
dt = 0.05
nstep = 500000
nstep_save = 500
nstep_save_rst = 500
neighbor_list_margin = 10.0
   # (optional) default is 10.0
viscosity_Pas = 0.00001
   # (optional) default is 0.00001

[Progress]
step = 1000

[variable_box]
step = 1000
change_x = -1.0
change_y = -1.0
change_z = -1.0
