title = "sis input"

[job]
type = "DCD"

[files]
      [files.in]
      ff = "./rna_cg1.ff"
      dcd = "md.dcd"

      [files.out]
      types = ["bp", "bpe"]
      prefix = "./test"


[repeat]
n_repeat = 47
n_chain = 64
