title = "sis input"

[job]
type = "DCD"

[files]
      [files.in]
      ff = "./rna_cg1_para2.ff"
      dcd = "./HBB2.dcd"
      fasta = "./beta-globin.fasta"

      [files.out]
      types = ["bp", "bpe", "bpall"]
      prefix = "./test"

[condition]
      tempK = 310.15
