title = "sis input"

[Job]
type = "MD"

[Files]
    [Files.In]
    ff = "../htv23-19.ff"
    fasta = "../T2S2HP.fasta"
    pdb_ini = "../T2S2HP_folded.pdb"

    [Files.Out]
    types = []
    prefix = "./test_REMD"

[Replica]
nrep_ion = 8

nstep_exchange = 10
nstep_save = 10
exchange = true

    [Replica.Ionic_strength]
    ## Ionic strength of the monovalent ions in molar (mol/L) units.
    1 = 0.02
    2 = 0.05
    3 = 0.10
    4 = 0.15
    5 = 0.20
    6 = 0.30
    7 = 0.50
    8 = 0.80

[Condition]
tempK = 300.00
rng_seed = 123

[MD]
integrator = "GJF-2GJ"
dt = 0.05
nstep = 10020
#nstep = 1000000000
nstep_save = 100
nstep_save_rst = 100
neighbor_list_margin = 10.0
viscosity_Pas = 0.00001

[Electrostatic]
ionic_strength = 0.15
cutoff_type = 2
cutoff = 10.0
#no_charge = [1, 27]
length_per_charge = 4.38178046

[Basepair]
model = 5
min_loop = 3
max_bp_per_nt = 1
#nstep_MC = 1
nstep_MC = 0

[Progress]
step = 1000
