title = "sis input"

[Job]
type = "MD"
#type = "CHECK_FORCE"

[Files]
    [Files.In]
    #ff = "./rna_cg1_triplet.ff"
    #ff = "../sis_dih_ReB_NN.ff"
    ff = "../htv23-19.ff"
    fasta = "../T2S2HP.fasta"
    pdb_ini = "../T2S2HP_folded.pdb"
    #xyz_ini = "T2S2HP_random.xyz"

    [Files.Out]
    #types = ["bpcoef", "bp", "bpall"]
    types = []
    prefix = "./test_REMD"

[Replica]
nrep_temp = 8

nstep_exchange = 10
nstep_save = 10
exchange = true

   [Replica.Temperature]
   1 = 293.15
   2 = 303.15
   3 = 313.15
   4 = 323.15
   5 = 333.15
   6 = 343.15
   7 = 353.15
   8 = 363.15

[Condition]
tempK = 300.00
rng_seed = 123

[MD]
integrator = "GJF-2GJ"
dt = 0.05
nstep = 10020
#nstep = 1000000000
nstep_save = 100
nstep_save_rst = 100
neighbor_list_margin = 10.0
viscosity_Pas = 0.00001

[Electrostatic]
ionic_strength = 0.15
cutoff_type = 2
cutoff = 10.0
#no_charge = [1, 27]
length_per_charge = 4.38178046

[Basepair]
model = 5
min_loop = 3
max_bp_per_nt = 1
#nstep_MC = 1
nstep_MC = 0

[Progress]
step = 1000
