title = "sis input"

[Job]
type = "MD"

[Files]
    [Files.In]
    ff = "../htv23-19.ff"
    fasta = "../T2S2HP.fasta"
    pdb_ini = "../T2S2HP_folded.pdb"

    [Files.Out]
    types = []
    prefix = "./test_REMD1"

[Replica]
nrep_temp = 0
nrep_force = 8

nstep_exchange = 100
nstep_save = 100
exchange = true

   [Replica.Force]
   1 = 0.0
   2 = 4.0
   3 = 8.0
   4 = 10.0
   5 = 12.0
   6 = 14.0
   7 = 16.0
   8 = 18.0

[Tweezers]
    [Tweezers.Dual_Constant_Force]
    id_pairs = [[1, 27],]
    forces_pN = [[1.0, 0.0, 0.0],]

[Condition]
tempK = 300.00
rng_seed = 123

[MD]
integrator = "GJF-2GJ"
dt = 0.05
nstep = 2000
nstep_save = 100
nstep_save_rst = 1000
neighbor_list_margin = 10.0
viscosity_Pas = 0.00001
fix_com_origin = 1

[Basepair]
model = 5
min_loop = 3
max_bp_per_nt = 1
nstep_MC = 10

[Progress]
step = 1000
